// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const prismaDatasourceUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
// const prismaDatasourceUrl = process.env.DATABASE_URL;

if (!prismaDatasourceUrl) {
	throw new Error(
		'Either DIRECT_URL or DATABASE_URL must be set for Prisma CLI.',
	);
}

export default defineConfig({
	schema: 'prisma',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: prismaDatasourceUrl,
	},
});
